name: ساخت APK

on:
  push:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کدها
        uses: actions/checkout@v3

      - name: نصب Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: نصب Buildozer و وابستگی‌ها
        run: |
          sudo apt update
          sudo apt install -y git zip unzip python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install buildozer cython

      - name: پذیرش مجوزهای اندروید (قبل از ساخت)
        run: |
          # buildozer را یک بار با دستور dummy اجرا می‌کنیم تا sdkmanager نصب شود
          buildozer android debug || true
          # حالا با دستور yes تمام مجوزها را می‌پذیریم
          yes | ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses

      - name: ساخت APK با Buildozer
        run: |
          buildozer android debug

      - name: آپلود APK
        uses: actions/upload-artifact@v4
        with:
          name: my-pdf-app
          path: bin/*.apk
