name: ساخت APK با Docker (expect)

on:
  push:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کدها
        uses: actions/checkout@v3

      - name: ساخت ایمیج سفارشی
        run: docker build -t my-buildozer .

      - name: ساخت APK
        run: |
          docker run --rm \
            -v $PWD:/home/user/hostapp \
            -w /home/user/hostapp \
            my-buildozer android debug

      - name: آپلود APK
        uses: actions/upload-artifact@v4
        with:
          name: my-pdf-app
          path: bin/*.apk
